# Generated by Django 3.2.4 on 2021-06-07 16:50

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('samples_per_day', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('duration', models.CharField(help_text='Duration in hours', max_length=2)),
                ('sample_count', models.CharField(help_text='# of samples to process', max_length=2)),
                ('assay', models.ManyToManyField(help_text='Select an Assay for this process', to='labmodel.Assay')),
            ],
        ),
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('days_per_month', models.CharField(help_text='Enter assumption for working days per month', max_length=2, verbose_name='days_per_month')),
                ('integrated_hours', models.CharField(help_text='Enter assumption for integrated hours per day', max_length=2, verbose_name='integrated_hours')),
                ('walkup_hours', models.CharField(help_text='Enter assumption for walkup hours per day', max_length=2, verbose_name='walkup_hours')),
                ('assay', models.ManyToManyField(help_text='Select an assay for this lab', to='labmodel.Assay')),
            ],
        ),
        migrations.CreateModel(
            name='InstrumentInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular instrument', primary_key=True, serialize=False)),
                ('identical_copies', models.CharField(max_length=2)),
                ('integrated_or_walkup', models.CharField(blank=True, choices=[('i', 'Integrated'), ('w', 'Walkup')], default='i', help_text='Integrated or walkup?', max_length=1)),
                ('instrument', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='labmodel.instrument')),
                ('process', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='labmodel.process')),
            ],
        ),
    ]
