# Generated by Django 3.2.4 on 2021-06-24 19:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('samples_per_batch', models.IntegerField(verbose_name='Samples per batch')),
                ('projection_for_year_1', models.IntegerField(verbose_name='Projection for next year')),
                ('projection_for_year_2', models.IntegerField(verbose_name='Projection for 2 years from now')),
                ('projection_for_year_3', models.IntegerField(verbose_name='Projection for 3 years from now')),
                ('projection_for_year_4', models.IntegerField(verbose_name='Projection for 4 years from now')),
                ('projection_for_year_5', models.IntegerField(verbose_name='Projection for 5 years from now')),
                ('projection_for_year_6', models.IntegerField(verbose_name='Projection for 6 years from now')),
            ],
        ),
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='InstrumentInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular instrument', primary_key=True, serialize=False)),
                ('samples_per_day', models.IntegerField()),
                ('identical_copies', models.IntegerField()),
                ('integrated_or_walkup', models.CharField(blank=True, choices=[('i', 'Integrated'), ('w', 'Walkup')], default='i', help_text='Integrated or walkup?', max_length=1)),
                ('instrument', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='labmodel.instrument')),
            ],
        ),
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('current_year', models.IntegerField(default=2021, verbose_name='Starting Year')),
                ('days_per_month', models.IntegerField(help_text='Enter assumption for working days per month', verbose_name='Days per month')),
                ('integrated_hours', models.DecimalField(decimal_places=2, help_text='Enter assumption for integrated hours per day', max_digits=4, verbose_name='Integrated Hours')),
                ('walkup_hours', models.DecimalField(decimal_places=2, help_text='Enter assumption for walkup hours per day', max_digits=4, verbose_name='Walkup Hours')),
                ('max_utilization', models.DecimalField(decimal_places=2, help_text='Enter the instrument maximum utilization in %', max_digits=4, verbose_name='Max utilization')),
                ('offset', models.DecimalField(decimal_places=2, help_text='Offset is the factor multiplied to duration estimates', max_digits=4, verbose_name='Offset')),
                ('from_template', models.BooleanField(default=False)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='LabAnalysis',
            fields=[
                ('lab', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='labmodel.lab')),
            ],
        ),
        migrations.CreateModel(
            name='ProcessInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subname', models.CharField(max_length=25)),
                ('duration', models.DecimalField(decimal_places=2, help_text='Duration in hours', max_digits=4)),
                ('sample_count', models.IntegerField(help_text='# of samples to process')),
                ('assay', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.RESTRICT, to='labmodel.assay')),
                ('instrumentinstance', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.RESTRICT, to='labmodel.instrumentinstance')),
                ('process', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.RESTRICT, to='labmodel.process')),
            ],
            options={
                'verbose_name': 'ProcessInstance',
                'verbose_name_plural': 'ProcessInstances',
            },
        ),
        migrations.AddField(
            model_name='assay',
            name='lab',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='labmodel.lab'),
        ),
    ]
