# Generated by Django 3.2.4 on 2021-06-24 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('labmodel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processinstance',
            name='instrumentinstance',
        ),
        migrations.AddField(
            model_name='processinstance',
            name='instrument',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.RESTRICT, to='labmodel.instrument'),
        ),
    ]
