# Generated by Django 3.2.4 on 2021-06-07 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labmodel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instrumentinstance',
            name='process',
        ),
        migrations.RemoveField(
            model_name='process',
            name='assay',
        ),
        migrations.AddField(
            model_name='assay',
            name='processes',
            field=models.ManyToManyField(help_text='Select processes for this assay', to='labmodel.Process'),
        ),
        migrations.AddField(
            model_name='process',
            name='instruments',
            field=models.ManyToManyField(help_text='Select instrument instances for this process', to='labmodel.InstrumentInstance'),
        ),
        migrations.AlterField(
            model_name='instrumentinstance',
            name='identical_copies',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='process',
            name='duration',
            field=models.CharField(help_text='Duration in hours', max_length=10),
        ),
        migrations.AlterField(
            model_name='process',
            name='sample_count',
            field=models.CharField(help_text='# of samples to process', max_length=10),
        ),
    ]
