# Generated by Django 3.2.4 on 2021-06-28 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('labmodel', '0002_auto_20210624_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrumentinstance',
            name='integrated_or_walkup',
            field=models.CharField(blank=True, choices=[('Integrated', 'Integrated'), ('Walkup', 'Walkup')], default='i', help_text='Integrated or walkup?', max_length=10),
        ),
        migrations.AlterField(
            model_name='processinstance',
            name='assay',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='labmodel.assay'),
        ),
        migrations.AlterField(
            model_name='processinstance',
            name='instrument',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='labmodel.instrument'),
        ),
    ]
