# Generated by Django 3.2.4 on 2021-06-08 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('labmodel', '0003_lab_creator'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assay',
            options={'verbose_name': 'Assay', 'verbose_name_plural': 'Assays'},
        ),
        migrations.RemoveField(
            model_name='lab',
            name='assay',
        ),
        migrations.AddField(
            model_name='assay',
            name='lab',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='labmodel.lab'),
        ),
    ]
