# Generated by Django 3.2.4 on 2021-06-08 20:25

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('labmodel', '0004_auto_20210608_1210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assay',
            name='processes',
        ),
        migrations.RemoveField(
            model_name='process',
            name='instruments',
        ),
        migrations.AddField(
            model_name='instrumentinstance',
            name='process',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.RESTRICT, to='labmodel.process'),
        ),
        migrations.CreateModel(
            name='ProcessInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular process instance', primary_key=True, serialize=False)),
                ('subname', models.CharField(max_length=25)),
                ('assay', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.RESTRICT, to='labmodel.assay')),
                ('process', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.RESTRICT, to='labmodel.process')),
            ],
        ),
    ]
