# Generated by Django 3.2.4 on 2021-06-29 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('labmodel', '0004_alter_instrumentinstance_instrument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processinstance',
            name='process',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='labmodel.process'),
        ),
    ]
