# Generated by Django 3.2.4 on 2021-06-10 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labmodel', '0005_auto_20210608_1325'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assay',
            options={},
        ),
    ]
