# Generated by Django 3.2.4 on 2021-07-27 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labmodel', '0006_labanalysis_failure_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labanalysis',
            name='failure_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='Failure Rate'),
        ),
    ]
