# Generated by Django 3.2.4 on 2021-08-06 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labmodel', '0007_alter_labanalysis_failure_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='processinstance',
            name='only_walkup',
            field=models.BooleanField(default=False, help_text='True if the process cannot be automated'),
        ),
    ]
